# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RemoteCam.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fRemoteCam.proto\x12\x0eRemoteCamProto\"&\n\x10GetConfigRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\x05\"\x90\x01\n\x11GetConfigResponse\x12\x13\n\x0bresponse_id\x18\x01 \x01(\x05\x12\x19\n\rcamera_matrix\x18\x02 \x03(\x02\x42\x02\x10\x01\x12\x17\n\x0b\x64ist_coeffs\x18\x03 \x03(\x02\x42\x02\x10\x01\x12\x13\n\x0b\x64\x65pth_scale\x18\x04 \x01(\x02\x12\r\n\x05width\x18\x05 \x01(\x05\x12\x0e\n\x06height\x18\x06 \x01(\x05\"%\n\x0fGetImageRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\x05\"Y\n\x10GetImageResponse\x12\x13\n\x0bresponse_id\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x11\n\x05\x63olor\x18\x04 \x03(\x05\x42\x02\x10\x01\"-\n\x17GetImageDepthmapRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\x05\"t\n\x18GetImageDepthmapResponse\x12\x13\n\x0bresponse_id\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x11\n\x05\x63olor\x18\x04 \x03(\x05\x42\x02\x10\x01\x12\x11\n\x05\x64\x65pth\x18\x05 \x03(\x05\x42\x02\x10\x01\x32\x9e\x02\n\x0eRemoteCamProto\x12R\n\tGetConfig\x12 .RemoteCamProto.GetConfigRequest\x1a!.RemoteCamProto.GetConfigResponse\"\x00\x12O\n\x08GetImage\x12\x1f.RemoteCamProto.GetImageRequest\x1a .RemoteCamProto.GetImageResponse\"\x00\x12g\n\x10GetImageDepthmap\x12\'.RemoteCamProto.GetImageDepthmapRequest\x1a(.RemoteCamProto.GetImageDepthmapResponse\"\x00\x42@\n%io.grpc.custom.Disinfection.RemoteCamB\x0eRemoteCamProtoP\x01\xa2\x02\x04\x46\x44\x44Ob\x06proto3')



_GETCONFIGREQUEST = DESCRIPTOR.message_types_by_name['GetConfigRequest']
_GETCONFIGRESPONSE = DESCRIPTOR.message_types_by_name['GetConfigResponse']
_GETIMAGEREQUEST = DESCRIPTOR.message_types_by_name['GetImageRequest']
_GETIMAGERESPONSE = DESCRIPTOR.message_types_by_name['GetImageResponse']
_GETIMAGEDEPTHMAPREQUEST = DESCRIPTOR.message_types_by_name['GetImageDepthmapRequest']
_GETIMAGEDEPTHMAPRESPONSE = DESCRIPTOR.message_types_by_name['GetImageDepthmapResponse']
GetConfigRequest = _reflection.GeneratedProtocolMessageType('GetConfigRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCONFIGREQUEST,
  '__module__' : 'RemoteCam_pb2'
  # @@protoc_insertion_point(class_scope:RemoteCamProto.GetConfigRequest)
  })
_sym_db.RegisterMessage(GetConfigRequest)

GetConfigResponse = _reflection.GeneratedProtocolMessageType('GetConfigResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETCONFIGRESPONSE,
  '__module__' : 'RemoteCam_pb2'
  # @@protoc_insertion_point(class_scope:RemoteCamProto.GetConfigResponse)
  })
_sym_db.RegisterMessage(GetConfigResponse)

GetImageRequest = _reflection.GeneratedProtocolMessageType('GetImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETIMAGEREQUEST,
  '__module__' : 'RemoteCam_pb2'
  # @@protoc_insertion_point(class_scope:RemoteCamProto.GetImageRequest)
  })
_sym_db.RegisterMessage(GetImageRequest)

GetImageResponse = _reflection.GeneratedProtocolMessageType('GetImageResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETIMAGERESPONSE,
  '__module__' : 'RemoteCam_pb2'
  # @@protoc_insertion_point(class_scope:RemoteCamProto.GetImageResponse)
  })
_sym_db.RegisterMessage(GetImageResponse)

GetImageDepthmapRequest = _reflection.GeneratedProtocolMessageType('GetImageDepthmapRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETIMAGEDEPTHMAPREQUEST,
  '__module__' : 'RemoteCam_pb2'
  # @@protoc_insertion_point(class_scope:RemoteCamProto.GetImageDepthmapRequest)
  })
_sym_db.RegisterMessage(GetImageDepthmapRequest)

GetImageDepthmapResponse = _reflection.GeneratedProtocolMessageType('GetImageDepthmapResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETIMAGEDEPTHMAPRESPONSE,
  '__module__' : 'RemoteCam_pb2'
  # @@protoc_insertion_point(class_scope:RemoteCamProto.GetImageDepthmapResponse)
  })
_sym_db.RegisterMessage(GetImageDepthmapResponse)

_REMOTECAMPROTO = DESCRIPTOR.services_by_name['RemoteCamProto']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%io.grpc.custom.Disinfection.RemoteCamB\016RemoteCamProtoP\001\242\002\004FDDO'
  _GETCONFIGRESPONSE.fields_by_name['camera_matrix']._options = None
  _GETCONFIGRESPONSE.fields_by_name['camera_matrix']._serialized_options = b'\020\001'
  _GETCONFIGRESPONSE.fields_by_name['dist_coeffs']._options = None
  _GETCONFIGRESPONSE.fields_by_name['dist_coeffs']._serialized_options = b'\020\001'
  _GETIMAGERESPONSE.fields_by_name['color']._options = None
  _GETIMAGERESPONSE.fields_by_name['color']._serialized_options = b'\020\001'
  _GETIMAGEDEPTHMAPRESPONSE.fields_by_name['color']._options = None
  _GETIMAGEDEPTHMAPRESPONSE.fields_by_name['color']._serialized_options = b'\020\001'
  _GETIMAGEDEPTHMAPRESPONSE.fields_by_name['depth']._options = None
  _GETIMAGEDEPTHMAPRESPONSE.fields_by_name['depth']._serialized_options = b'\020\001'
  _GETCONFIGREQUEST._serialized_start=35
  _GETCONFIGREQUEST._serialized_end=73
  _GETCONFIGRESPONSE._serialized_start=76
  _GETCONFIGRESPONSE._serialized_end=220
  _GETIMAGEREQUEST._serialized_start=222
  _GETIMAGEREQUEST._serialized_end=259
  _GETIMAGERESPONSE._serialized_start=261
  _GETIMAGERESPONSE._serialized_end=350
  _GETIMAGEDEPTHMAPREQUEST._serialized_start=352
  _GETIMAGEDEPTHMAPREQUEST._serialized_end=397
  _GETIMAGEDEPTHMAPRESPONSE._serialized_start=399
  _GETIMAGEDEPTHMAPRESPONSE._serialized_end=515
  _REMOTECAMPROTO._serialized_start=518
  _REMOTECAMPROTO._serialized_end=804
# @@protoc_insertion_point(module_scope)
